In [17]:
import pandas as pd

In [21]:
df1 = pd.read_excel("bitre_fatalities_dec2024.xlsx",sheet_name="BITRE_Fatality")
df1.to_csv("temp2.csv", index=False)
df1 = pd.read_csv("temp2.csv",skiprows=2,header=2)
print(df1.tail(10))

       Crash ID State  Month  Year    Dayweek      Time Crash Type  \
56864  19891246   NSW      1  1989  Wednesday  17:05:00     Single
56865  19892038   Vic      1  1989  Wednesday  18:50:00     Single
56866  19894064    SA      1  1989  Wednesday  19:00:00   Multiple
56867  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56868  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56869  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56870  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56871  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56872  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56873  19895133    WA      1  1989  Wednesday  21:00:00   Multiple

      Bus Involvement Heavy Rigid Truck Involvement  \
56864             Yes                            -9
56865             Yes                            No
56866              No                            -9
56867              No                            -9
56868              No                            -9
56869              No                            -9
56870              No                            -9
56871              No                            -9
56872              No                            -9
56873              No                            -9

      Articulated Truck Involvement  ... Age National Remoteness Areas  \
56864                            No  ...   5                   Unknown
56865                            No  ...  15                   Unknown
56866                            No  ...  22                   Unknown
56867                           Yes  ...  13                   Unknown
56868                           Yes  ...  11                   Unknown
56869                           Yes  ...  13                   Unknown
56870                           Yes  ...  13                   Unknown
56871                           Yes  ...  18                   Unknown
56872                           Yes  ...  14                   Unknown
56873                            No  ...  70                   Unknown

      SA4 Name 2021  National LGA Name 2021 National Road Type  \
56864           NaN                     NaN       Undetermined
56865           NaN                     NaN       Undetermined
56866           NaN                     NaN       Undetermined
56867           NaN                     NaN       Undetermined
56868           NaN                     NaN       Undetermined
56869           NaN                     NaN       Undetermined
56870           NaN                     NaN       Undetermined
56871           NaN                     NaN       Undetermined
56872           NaN                     NaN       Undetermined
56873           NaN                     NaN       Undetermined

      Christmas Period Easter Period Age Group Day of week Time of day
56864               No            No   0_to_16     Weekday         Day
56865               No            No   0_to_16     Weekday       Night
56866               No            No  17_to_25     Weekday       Night
56867               No            No   0_to_16     Weekday       Night
56868               No            No   0_to_16     Weekday       Night
56869               No            No   0_to_16     Weekday       Night
56870               No            No   0_to_16     Weekday       Night
56871               No            No  17_to_25     Weekday       Night
56872               No            No   0_to_16     Weekday       Night
56873               No            No  65_to_74     Weekday       Night

[10 rows x 23 columns]

/var/folders/1x/tzng_1pj7r199d3k835jz6_80000gn/T/ipykernel_2960/2305155041.py:3: DtypeWarning: Columns (10,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("temp2.csv",skiprows=2,header=2)

In [22]:
df2 = pd.read_excel("bitre_fatal_crashes_dec2024.xlsx",sheet_name="BITRE_Fatal_Crash")
df2.to_csv("temp.csv1", index=False)
df2 = pd.read_csv("temp.csv1",skiprows=2,header=2)
print(df2.tail(10))
df2.iloc[:, [11, 13, 14]].tail(10)

       Crash ID State  Month  Year    Dayweek      Time Crash Type  \
51274  19891555   NSW      1  1989  Wednesday  14:45:00   Multiple
51275  19892354   Vic      1  1989  Wednesday  15:27:00   Multiple
51276  19891465   NSW      1  1989  Wednesday  15:30:00     Single
51277  19891215   NSW      1  1989  Wednesday  15:50:00   Multiple
51278  19894128    SA      1  1989  Wednesday  16:10:00     Single
51279  19891246   NSW      1  1989  Wednesday  17:05:00     Single
51280  19892038   Vic      1  1989  Wednesday  18:50:00     Single
51281  19894064    SA      1  1989  Wednesday  19:00:00   Multiple
51282  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
51283  19895133    WA      1  1989  Wednesday  21:00:00   Multiple

       Number Fatalities Bus \nInvolvement Heavy Rigid Truck Involvement  \
51274                  1                No                            -9
51275                  1                No                            No
51276                  1                No                            -9
51277                  3                No                            -9
51278                  1                No                            -9
51279                  1               Yes                            -9
51280                  1               Yes                            No
51281                  1                No                            -9
51282                  6                No                            -9
51283                  1                No                            -9

      Articulated Truck Involvement Speed Limit National Remoteness Areas  \
51274                            No          60                   Unknown
51275                           Yes          75                   Unknown
51276                            No          60                   Unknown
51277                            No         100                   Unknown
51278                            No          60                   Unknown
51279                            No          60                   Unknown
51280                            No          60                   Unknown
51281                            No         100                   Unknown
51282                           Yes         100                   Unknown
51283                            No          -9                   Unknown

      SA4 Name 2021 National LGA Name 2021 National Road Type  \
51274           NaN                    NaN       Undetermined
51275           NaN                    NaN       Undetermined
51276           NaN                    NaN       Undetermined
51277           NaN                    NaN       Undetermined
51278           NaN                    NaN       Undetermined
51279           NaN                    NaN       Undetermined
51280           NaN                    NaN       Undetermined
51281           NaN                    NaN       Undetermined
51282           NaN                    NaN       Undetermined
51283           NaN                    NaN       Undetermined

      Christmas Period Easter Period Day of week Time of Day
51274               No            No     Weekday         Day
51275               No            No     Weekday         Day
51276               No            No     Weekday         Day
51277               No            No     Weekday         Day
51278               No            No     Weekday         Day
51279               No            No     Weekday         Day
51280               No            No     Weekday       Night
51281               No            No     Weekday       Night
51282               No            No     Weekday       Night
51283               No            No     Weekday       Night

/var/folders/1x/tzng_1pj7r199d3k835jz6_80000gn/T/ipykernel_2960/2613331120.py:3: DtypeWarning: Columns (11,13,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("temp.csv1",skiprows=2,header=2)

      Speed Limit SA4 Name 2021 National LGA Name 2021
51274          60           NaN                    NaN
51275          75           NaN                    NaN
51276          60           NaN                    NaN
51277         100           NaN                    NaN
51278          60           NaN                    NaN
51279          60           NaN                    NaN
51280          60           NaN                    NaN
51281         100           NaN                    NaN
51282         100           NaN                    NaN
51283          -9           NaN                    NaN

In [39]:
merged_df = pd.merge(df1, df2, on=['Crash ID', 'Time', 'State', 'Month', 'Year', 'Dayweek', 
                                    'Crash Type', 'Heavy Rigid Truck Involvement',
                                    'Articulated Truck Involvement', 'Speed Limit', 
                                    'National Remoteness Areas', 'SA4 Name 2021', 
                                    'National LGA Name 2021', 'National Road Type'], how='left')

print(merged_df)

       Crash ID State  Month  Year    Dayweek      Time Crash Type  \
0      20241115   NSW     12  2024     Friday  04:00:00     Single
1      20241125   NSW     12  2024     Friday  06:15:00     Single
2      20246013   Tas     12  2024     Friday  09:43:00   Multiple
3      20241002   NSW     12  2024     Friday  10:35:00   Multiple
4      20242261   Vic     12  2024     Friday  11:30:00   Multiple
...         ...   ...    ...   ...        ...       ...        ...
56869  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56870  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56871  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56872  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56873  19895133    WA      1  1989  Wednesday  21:00:00   Multiple

      Bus Involvement Heavy Rigid Truck Involvement  \
0                  No                            No
1                  No                            No
2                  No                            No
3                  No                            No
4                  -9                            -9
...               ...                           ...
56869              No                            -9
56870              No                            -9
56871              No                            -9
56872              No                            -9
56873              No                            -9

      Articulated Truck Involvement  ... Easter Period_x Age Group  \
0                                No  ...              No  65_to_74
1                                No  ...              No  17_to_25
2                                No  ...              No  26_to_39
3                                No  ...              No  26_to_39
4                                -9  ...              No  40_to_64
...                             ...  ...             ...       ...
56869                           Yes  ...              No   0_to_16
56870                           Yes  ...              No   0_to_16
56871                           Yes  ...              No  17_to_25
56872                           Yes  ...              No   0_to_16
56873                            No  ...              No  65_to_74

      Day of week_x  Time of day Number Fatalities Bus \nInvolvement  \
0           Weekday        Night               1.0                No
1           Weekday          Day               1.0                No
2           Weekday          Day               1.0                No
3           Weekday          Day               1.0                No
4           Weekday          Day               1.0                -9
...             ...          ...               ...               ...
56869       Weekday        Night               6.0                No
56870       Weekday        Night               6.0                No
56871       Weekday        Night               6.0                No
56872       Weekday        Night               6.0                No
56873       Weekday        Night               1.0                No

      Christmas Period_y Easter Period_y Day of week_y Time of Day
0                    Yes              No       Weekday       Night
1                     No              No       Weekday         Day
2                    Yes              No       Weekday         Day
3                     No              No       Weekday         Day
4                     No              No       Weekday         Day
...                  ...             ...           ...         ...
56869                 No              No       Weekday       Night
56870                 No              No       Weekday       Night
56871                 No              No       Weekday       Night
56872                 No              No       Weekday       Night
56873                 No              No       Weekday       Night

[56874 rows x 29 columns]

In [41]:
merged_df.to_csv("merge.csv", index=False)

In [44]:
header=['National LGA Name 2021','Dwelling Records','add']
transactions = pd.read_csv('LGA.csv', skiprows=12,header=None)
transactions.columns = header
transactions[transactions.columns[1]] = pd.to_numeric(transactions[transactions.columns[1]], errors='coerce')
transactions = transactions.dropna(subset=[transactions.columns[1]])
transactions.iloc[:, :2].to_csv('processed_LGA.csv', index=False)

In [47]:
lga_df=pd.read_csv('processed_LGA.csv')

In [51]:
df = pd.merge(merged_df, lga_df, on=['National LGA Name 2021'], how='left')

In [55]:
print(df)
df.to_csv("lga.csv", index=False)

       Crash ID State  Month  Year    Dayweek      Time Crash Type  \
0      20241115   NSW     12  2024     Friday  04:00:00     Single
1      20241125   NSW     12  2024     Friday  06:15:00     Single
2      20246013   Tas     12  2024     Friday  09:43:00   Multiple
3      20241002   NSW     12  2024     Friday  10:35:00   Multiple
4      20242261   Vic     12  2024     Friday  11:30:00   Multiple
...         ...   ...    ...   ...        ...       ...        ...
56869  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56870  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56871  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56872  19896006   Tas      1  1989  Wednesday  20:20:00   Multiple
56873  19895133    WA      1  1989  Wednesday  21:00:00   Multiple

      Bus Involvement Heavy Rigid Truck Involvement  \
0                  No                            No
1                  No                            No
2                  No                            No
3                  No                            No
4                  -9                            -9
...               ...                           ...
56869              No                            -9
56870              No                            -9
56871              No                            -9
56872              No                            -9
56873              No                            -9

      Articulated Truck Involvement  ... Age Group Day of week_x Time of day  \
0                                No  ...  65_to_74       Weekday       Night
1                                No  ...  17_to_25       Weekday         Day
2                                No  ...  26_to_39       Weekday         Day
3                                No  ...  26_to_39       Weekday         Day
4                                -9  ...  40_to_64       Weekday         Day
...                             ...  ...       ...           ...         ...
56869                           Yes  ...   0_to_16       Weekday       Night
56870                           Yes  ...   0_to_16       Weekday       Night
56871                           Yes  ...  17_to_25       Weekday       Night
56872                           Yes  ...   0_to_16       Weekday       Night
56873                            No  ...  65_to_74       Weekday       Night

       Number Fatalities Bus \nInvolvement Christmas Period_y Easter Period_y  \
0                    1.0                No                Yes              No
1                    1.0                No                 No              No
2                    1.0                No                Yes              No
3                    1.0                No                 No              No
4                    1.0                -9                 No              No
...                  ...               ...                ...             ...
56869                6.0                No                 No              No
56870                6.0                No                 No              No
56871                6.0                No                 No              No
56872                6.0                No                 No              No
56873                1.0                No                 No              No

      Day of week_y Time of Day Dwelling Records
0           Weekday       Night          28244.0
1           Weekday         Day          25523.0
2           Weekday         Day           6444.0
3           Weekday         Day          12955.0
4           Weekday         Day              NaN
...             ...         ...              ...
56869       Weekday       Night              NaN
56870       Weekday       Night              NaN
56871       Weekday       Night              NaN
56872       Weekday       Night              NaN
56873       Weekday       Night              NaN

[56874 rows x 30 columns]